export const INDIA_BANKS: string[] = [
  // Public sector banks
  'Bank of Baroda',
  'Bank of India',
  'Bank of Maharashtra',
  'Canara Bank',
  'Central Bank of India',
  'Indian Bank',
  'Indian Overseas Bank',
  'Jammu & Kashmir Bank',
  'Punjab & Sind Bank',
  'Punjab National Bank',
  'State Bank of India',
  'UCO Bank',
  'Union Bank of India',
  // Private sector banks
  'Axis Bank',
  'Bandhan Bank',
  'CSB Bank',
  'City Union Bank',
  'DCB Bank',
  'Dhanlaxmi Bank',
  'Federal Bank',
  'HDFC Bank',
  'ICICI Bank',
  'IDBI Bank',
  'IndusInd Bank',
  'Karnataka Bank',
  'Karur Vysya Bank',
  'Kotak Mahindra Bank',
  'Nainital Bank',
  'RBL Bank',
  'South Indian Bank',
  'Tamilnad Mercantile Bank',
  'Yes Bank',
  // Payments banks
  'Airtel Payments Bank',
  'India Post Payments Bank',
  'Jio Payments Bank',
  'NSDL Payments Bank',
  // Small finance banks
  'AU Small Finance Bank',
  'Capital Small Finance Bank',
  'Equitas Small Finance Bank',
  'ESAF Small Finance Bank',
  'Fino Small Finance Bank',
  'Jana Small Finance Bank',
  'Shivalik Small Finance Bank',
  'Slice Small Finance Bank',
  'Suryoday Small Finance Bank',
  'Ujjivan Small Finance Bank',
  'Unity Small Finance Bank',
  'Utkarsh Small Finance Bank',
  // Local area banks
  'Coastal Local Area Bank',
  'Krishna Bhima Samruddhi Local Area Bank'
];
